
services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pfin
    ports:
      - '5432:5432'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      DATABASE_HOST: database
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: pfin
      DATABASE_PORT: 5432
      DATABASE_TIMEZONE: Asia/Bangkok
    depends_on:
      - database
    restart: always


    
